stages:
    - ⚙️ Build️

variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
    NODE_VERSION: "18"

# Cache dependencies for faster builds
cache:
    paths:
        - .gradle/
        - build/

# Java backend build job
Backend:
    stage: ⚙️ Build️
    image: gradle:8.6-jdk21
    before_script:
        - cd $CI_PROJECT_DIR
    script:
        - echo "Building Backend"
        - gradle assemble
    artifacts:
        paths:
            - '**/build/libs/*.jar'
        expire_in: 1 week

# Frontend build job
Frontend:
    stage: ⚙️ Build️
    image: node:${NODE_VERSION}
    script:
        - echo "Building Frontend"
        - cd client
        - npm install
        - npm run build
    artifacts:
        paths:
            - client/dist/
        expire_in: 1 week
